### ISSUE TITLE
启用插件的时候报错

### ISSUE THREAD

**Issue by wenfer** [CharmeRyl/typecho-plugin-ossfile#2]
没有打印错误信息，就是Server Error
不知道跟phar有没有关系

**Comment by jqjiang819** [comment]
你可以试一下第一个版本，可能是你的php不支持phar
如果还是不行的话，提供一下你的运行环境以及版本，我测试一下
第一版：[typecho-plugin-ossfile-fef2cfc4281d53ce61d0574bfc96b4a2c3ac029f.zip](https://github.com/CharmeRyl/typecho-plugin-ossfile/files/2408337/typecho-plugin-ossfile-fef2cfc4281d53ce61d0574bfc96b4a2c3ac029f.zip)

**Comment by JoyChou93** [comment]
应该是修改下目录名称，typecho-plugin-ossfile修改为OssForTypecho

**Comment by jqjiang819** [comment]
嗯，不好意思，因为适配TeStore那边，我改了目录结构
建议使用[TeStore](https://github.com/typecho-fans/plugins/tree/master/TeStore)来安装插件，比较方便
