### ISSUE TITLE
考虑增加图片样式吗

### ISSUE THREAD

**Issue by eallion** [CharmeRyl/typecho-plugin-ossfile#5]
[https://help.aliyun.com/document_detail/48884.html?spm=5176.8466084.0.0.58d61450jAd9EC](https://help.aliyun.com/document_detail/48884.html?spm=5176.8466084.0.0.58d61450jAd9EC)

**Comment by jzwalk** [comment]
[Typecho Fans社区版](https://github.com/typecho-fans/plugins/tree/master/OssForTypecho)已代更

**Comment by eallion** [comment]
awesome!
